trigger:
- main
- staging
- dev
pr:
- main
- staging
- dev

pool:
  vmImage: ubuntu-latest

stages:
- template: ./gradle-build-test-stage-template.yml
  parameters:
    displayName: 'Backend Build & Test'

- stage:
  jobs:
  - job:
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          ls
          echo $(Pipeline.Workspace)
          ls $(Pipeline.Workspace)

- template: ./dockerize-template.yml
  parameters:
    displayName: 'Build Docker Image and Push'

- stage:
  jobs:
  - job:
    steps:
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'Alex-Dev-Cluster'
          manifests: '**/monolith-manifest.yml'
          rolloutStatusTimeout: '10'