trigger:
  - main
  - staging
  - dev
pr:
  - main
  - staging
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_and_Test
    jobs:
      - template: ./gradle-build-test-job-template.yml
        parameters:
          jobName: 'Build_and_Test'
          testPath: '**/TEST-*.xml'
          ccPath: 'build/classes/main/'
  - stage: Dockerize
    jobs:
      - template: ./dockerize-template.yml
        parameters:
          jobName: 'Dockerize'
          containerRegistry: 'project-3-docker-hub'
          repository: 'dajpearl/forge-backend'
          imageTag: '${{ variables.Build.SourceVersion }}'
          dockerPath: '**/gradle.Dockerfile'
  - stage: Deploy
    jobs:
      - template: ./kubernetes-template.yml
        parameters:
          jobName: 'Deploy'
          serviceConnection: 'Alex-Dev-Cluster'
          manifestPath: '**/backend-manifest.yml'
      - template: ./discord-job-template.yml
        parameters:
          dependOn: Deploy
          name: 'Team2-P3-Backend'
          title: 'Forge Portfolio Management System DevOps'
          discordVarGroup: Discord-Webhook-Info
            # parameters.discordVarGroup contains the name of a variable group set in Azure Pipelines > Library
            # the variable group contains two variables: discordid and discordkey
            # currently, the discordVarGroup is named Discord-Webhook-Info, 
            # but can be swapped out if you want to notify to multiple Discord webhooks.
