trigger:
- main
- staging
- dev
pr:
- main
- staging
- dev

pool:
  vmImage: ubuntu-latest

stages:
- template: ./gradle-build-test-stage-template.yml
  parameters:
    displayName: 'Backend Build & Test'

- template: ./dockerize-template.yml
  parameters:
    displayName: 'Build Docker Image and Push'