trigger:
  - main
  - dev
pr:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_Test_and_Dockerize
    jobs:
      - template: ./maven-build-test-job-template.yml
        parameters:
          jobName: 'Build_and_Test'
          serviceConnection: 'Forge-SonarCloud'
          organization: '1058-sophia-gavrila-forge'
          testPath: '**/surefire-reports/TEST-*.xml'
      - template: ./dockerize-template.yml
        parameters:
          jobName: 'Dockerize'
          containerRegistry: 'project-3-docker-hub'
          repository: 'dajpearl/forge-backend'
          imageTag: "$(Build.SourceVersion)"
          dockerPath: '**/mavenpipe.dockerfile'
  - stage: Deploy
    jobs:
      - template: ./kubernetes-template.yml
        parameters:
          jobName: 'Deploy'
          branchMain: 'refs/heads/azure-pipelines'
          serviceConnectionMain: 'Alex-Main-Cluster'
          serviceConnectionDev: 'Alex-Dev-Cluster'
          manifestPath: '**/backend_manifest.yaml'
      - template: ./discord-job-template.yml
        parameters:
          dependOn: Deploy
          name: 'Team2-P3-Backend'
          title: 'Forge Portfolio Management System DevOps'
          discordVarGroup: Discord-Webhook-Info
            # parameters.discordVarGroup contains the name of a variable group set in Azure Pipelines > Library
            # the variable group contains two variables: discordid and discordkey
            # currently, the discordVarGroup is named Discord-Webhook-Info, 
            # but can be swapped out if you want to notify to multiple Discord webhooks.
