parameters:
  - name: 'dependOn'
    type: string
  - name: 'name'
    type: string
  - name: 'title'
    type: string
jobs:
- job: DiscordMessage
  dependsOn: ${{ parameters.dependOn }}
  variables: 
  - group: Discord-Webhook-Info
  - name: discord_id
    value: $[variables.discordid]
  - name: discord_key
    value: $[variables.discordkey]
  steps:  
  - task: ado-discord-webhook@1
    inputs:
      channelId: $(variables.discordid)
      webhookKey: $(variables.discordkey)
      name: ${{ parameters.name }}
      messageType: 'content'
      content: |
        **${{ parameters.title }}**: $(Build.SourceVersionMessage)
        ```
        Build Number: $(Build.BuildNumber)
        Build Branch: $(Build.SourceBranch)
        Build Reason: $(Build.Reason)
        Commit Id: $(Build.SourceVersion)
        ```
        **Result**: $(Agent.JobStatus)
