steps: 
    - task: ado-discord-webhook@1
      dependsOn: ${{ parameters.dependOn }}
      variables: 
      - group: Discord-Webhook-Info
      - name: discord_id
        value: $[variables.discordid]
      - name: discord_key
        value: $[variables.discordkey]
      inputs:
        channelId: $(discord_id)
        webhookKey: $(discord_key)
        name: 'Team2-P3'
        messageType: 'content'
        content: |
          **Team 2 Project 3 Backend**: $(Build.SourceVersionMessage)
          ```
          Build Number: $(Build.BuildNumber)
          Build Branch: $(Build.SourceBranch)
          Build Reason: $(Build.Reason)
          Build Image: backend-$(Build.SourceVersion)
          ```
          **Result**: $(Agent.JobStatus)
          