parameters:
  - name: 'dependOn'
    type: string
  - name: 'name'
    type: string
  - name: 'title'
    type: string
jobs:
- job: DiscordMessage
  dependsOn: ${{ parameters.dependOn }}
  variables: 
  - group: Discord-Webhook-Info
  steps:  
  - task: ado-discord-webhook@1
    inputs:
      channelId: $[variables.discordid]
      webhookKey: $[variables.discordkey]
      name: 'P3T2'
      messageType: 'content'
      content: |
        **P3T2**: $(Build.SourceVersionMessage)
        ```
        Build Number: $(Build.BuildNumber)
        Build Branch: $(Build.SourceBranch)
        Build Reason: $(Build.Reason)
        Commit Id: $(Build.SourceVersion)
        ```
        **Result**: $(Agent.JobStatus)
