parameters:
  - name: 'dependOn'
    type: string
  - name: 'name'
    type: string
  - name: 'title'
    type: string
  - name: 'channelID' # Secret discord information, channelID and key
    type: string
  - name: 'webhookKey' # Secret discord information, channelID and key
    type: string
jobs:
  - job: DiscordMessage
    dependsOn: ${{ parameters.dependOn }}
    steps:
      - task: ado-discord-webhook@1
        inputs:
          channelId: '${{ parameters.channelID }}'
          webhookKey: '${{ parameters.webhookKey }}'
          name: ${{ parameters.name }}
          messageType: 'content'
          content: |
            **${{ parameters.title }}**: $(Build.SourceVersionMessage)
            ```
            Build Number: $(Build.BuildNumber)
            Build Branch: $(Build.SourceBranch)
            Build Reason: $(Build.Reason)
            Commit Id: $(Build.SourceVersion)
            ```
            **Result**: $(Agent.JobStatus)
