parameters:
  - name: 'jobName'
    type: string
  - name: 'containerRegistry' #service connection name
    type: string
  - name: 'repository' #dockerhub repository name
    type: string
  - name: 'imageTag' #docker image tag
    type: string
  - name: 'dockerPath' #docker file path
    type: string
jobs:
  - job:
    displayName: ${{ parameters.jobName }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'maven-output'
          targetPath: '$(Pipeline.Workspace)'
          publishLocation: 'pipeline'
      - script: |
          cd ..
          pwd
          find
          echo $(Build.Repository.LocalPath)
      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          containerRegistry: '${{ parameters.containerRegistry }}'
          repository: '${{ parameters.repository }}'
          command: 'build'
          Dockerfile: '${{ parameters.dockerPath }}'
          tags: '${{ parameters.imageTag }}'
          buildContext: $(Build.Repository.LocalPath)/..
          arguments: '--build-arg JAR_FILE=demo-0.0.1-SNAPSHOT.war'
      - task: Docker@2
        displayName: 'Docker Push'
        inputs:
          containerRegistry: '${{ parameters.containerRegistry }}'
          repository: '${{ parameters.repository }}'
          command: 'push'
          tags: '${{ parameters.imageTag }}'
