stages:
- stage:
  displayName: ${{ parameters.displayName }}
  jobs:
  - job:
    steps:
    - task: Docker@2
      inputs:
        repository: 'dajpearl/forge-backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.SourceVersion)'
