stages:
- stage: "Build & Test"
  displayName: ${{ parameters.displayName }}
  jobs:
  - job: "Build & Test"
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        codeCoverageClassFilesDirectories: 'build/classes/main/'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
  - template: ./discord-job-template.yml  