parameters:
  - name: 'jobName'
    type: string
  - name: 'testPath'
    type: string
  - name: 'ccPath'
    type: string
  
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'build'
          publishJUnitResults: true
          testResultsFiles: '${{ parameters.testPath }}'
          codeCoverageToolOption: 'JaCoCo'
          codeCoverageClassFilesDirectories: '${{ parameters.ccPath }}'
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false