parameters:
  - name: 'jobName'
    type: string
  - name: 'serviceConnection' #Kubernetes Service Connection name
    type: string
  - name: 'manifestPath' #Kubernetes manifest file path
    type: string
jobs:
  - job: ${{ parameters.jobName }}
    steps:
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: '${{ parameters.jobName }}'
          manifests: '${{ parameters.jobName }}'
          rolloutStatusTimeout: '10'
