steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Forge-SonarCloud'
    organization: '1058-sophia-gavrila-forge'
    scannerMode: 'Other'
    extraProperties: |
      sonar.branch.name=main
      sonar.projectKey=1058-Sophia-Gavrila-Forge_Forge-Backend
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageRestoreOriginalPomXml: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'