apiVersion: apps/v1
kind: Deployment #statefulset?
metadata:
  name: forge-backend
spec:
  selector:
    matchLabels:
      app: forge-backend
  template:
    metadata:
      labels:
        app: forge-backend
    spec:
      containers:
      - name: forge-backend
        image: #placeholder/image:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        ports:
        - containerPort: 8081
        # env:
        # envFrom:
        # - configmapRef:
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: forge-backend
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
