apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forge-backend.fullname" . }}
  labels:
    {{- include "forge-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "forge-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "forge-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "forge-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 8081
            protocol: TCP
            # envFrom:
            # - configMapRef:
            #   name: backend-config
            # - secretRef:
            #   name: backend-database-login
          env:
          - name: spring.h2.console.enabled
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: spring.h2.console.enabled
          - name: spring.datasource.url
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: spring.datasource.url
          - name: spring.datasource.driverClassName
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: spring.datasource.driverClassName
          - name: spring.jpa.database.platform
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: spring.jpa.database-platform

          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: backend-database-login
                key: username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: backend-database-login
                key: password
          

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
