apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.dbconfig.name }}
data:
  DB_URL: jdbc:{{ternary "postgresql://" "h2:" .Values.db.persist }}{{ternary (printf "%s:5432/postgres" .Values.db.service.name) "mem:testdb" .Values.db.persist }}
  server.port: {{ .Values.image.port | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.dbconfig.secretName }}
stringData:
  username: {{ .Values.dbconfig.login.username }}
  password: {{ .Values.dbconfig.login.password }}
