trigger:
  - main
  - dev

pr:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

parameters:
  - name: 'branchMain'
    type: string
    default: 'refs/heads/main'
  - name: 'branchDev'
    type: string
    default: 'refs/heads/dev'
  - name: 'mainCluster' 
    type: string
    default: 'may24-devops-team2-main-cluster'
  - name: 'devCluster' 
    type: string
    default: 'may24-devops-team2-dev-cluster'
  - name: 'containerRegistry'
    type: string
    default: 'acr-team2'
  - name: 'repository'
    type: string
    default: 'forge-bundle'
  - name: 'secretName'
    type: string
    default: 'p3-team2-acr'

resources:
 repositories:
   - repository: forgeFrontend
     type: github
     endpoint: 1058-Sophia-Gavrila-Forge
     name: 1058-Sophia-Gavrila-Forge/Portfolio-Frontend

stages:
  - stage:
    jobs:

      - job:
        steps:
          - checkout: none
          - script: echo hi

