apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbconfig.name }}
data:
{{- with .Values.dbconfig.datasource }}
  {{- toYaml . | nindent 2 }}
{{- end }}
  server.port: {{ .Values.deploy.port | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbconfig.secretName }}

stringData:
  username: {{ .Values.dbconfig.username }}
  password: {{ .Values.dbconfig.password }}
