apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.dbconfig.name }}
data:
{{- with .Values.db.persist }}
  spring.datasource.url: jdbc:{{ternary "postgresql://" "h2:" . }}{{ternary "mem:testdb"}}
{{- end }}
{{- with .Values.dbconfig.datasource }}
  spring.datasource.driverClassName: {{ .driverClassName | quote }}
  spring.jpa.database.platform: {{ .platform | quote }}
  spring.h2.console.enabled: {{ .h2enabled | quote }}
{{- end }}
  server.port: {{ .Values.deploy.port | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.dbconfig.secretName }}
stringData:
  username: {{ .Values.dbconfig.login.username }}
  password: {{ .Values.dbconfig.login.password }}
