apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forgeBackend.fullname" . }}
  labels:
    {{- include "forgeBackend.labels" . | nindent 4 }}
    part: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "forgeBackend.selectorLabels" . | nindent 6 }}
      part: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "forgeBackend.selectorLabels" . | nindent 8 }}
        part: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "forgeBackend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.deploy.portName }}
              containerPort: {{ .Values.deploy.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Values.dbconfig.name }}
          env:
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.dbconfig.secretName }}
                key: username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.dbconfig.secretName }}
                key: password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
