apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgeBackend.fullname" . }}
  labels:
    {{- include "forgeBackend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploy.portName }}
      protocol: TCP
      name: http
  selector:
    app: forge-backend
    version: 0.0.1
    project: forge
    part: backend
